### ISSUE TITLE
Support for Godot 4.x version

### ISSUE THREAD

**Issue by piszczu4** [milesturin/Godot-Destructable-Terrain#1]
Hi, is it project still maintained? I'm looking for exactly this feature for my Godot 4.3 project but this code is for 3.x version. Any change to get updated version?

**Comment by milesturin** [comment]
Hello, I originally made this for a project I was working on but abandoned. I posted the code under an MIT license in case someone might find it useful as a reference implementation, but I never really planned on maintaining it as a proper library.

It's been a while since I looked at this code, but off the top of my head it should not be difficult to port to Godot 4, it is most likely just a matter of replacing outdated Godot APIs with the newer versions of them. I am happy to accept a PR that ports it, but for the time being I do not have the bandwidth to do it myself.

I may revisit this in the future and make it an actual plugin.
